### ISSUE TITLE
How to make UAVCAN test_stm32f107?

### ISSUE THREAD

**Issue by BreederBai** [Zubax/zubax_chibios#9]
I want to compile examples of UAVCAN, but the tutorial here puzzles me. I don't know how to set up ChibiOS. This makes my job difficult. Can someone tell me the specific steps to complete the compilation work? I will Grateful!

**Comment by pavel-kirienko** [comment]
Hello,

I decided to remove the test application completely because it's outdated: https://github.com/UAVCAN/libuavcan/pull/125

Rather, use these apps as a reference:

- https://github.com/PX4/sapog
- https://github.com/Zubax/zubax_gnss
